binary-ghc-args:
- -O2
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8.1-unstable
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args: []
excluded-modules: []
